site_name: Keptn - Supercharge Your Deployments
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/keptn-icon-white.svg
  favicon: https://lifecycle.keptn.sh/images/logo-mobile.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.action.view
repo_name: keptn/lifecycle-toolkit
repo_url: https://github.com/keptn/lifecycle-toolkit
site_url: https://lifecycle.keptn.sh
edit_uri: edit/main/docs/
site_description: >-
  Achieve cloud-native application lifecycle orchestration with Keptn.
  Enhance Kubernetes monitoring, streamline metrics ingestion, and
  automate deployment validation. Join the Keptn community for insights.
extra_javascript:
  - assets/versions.js
plugins:
  - social
  - include-markdown:
      trailing_newlines: false
  - git-revision-date-localized

nav:
  - index.md
  - Tests: tests.md
  - Core Concepts: intro/index.md
  - Get Started:
      - getting-started/index.md
      - Get started with Metrics: getting-started/metrics.md
  - Installation:
      - install/index.md
      - Install Keptn: install/install.md
  - Guides:
      - guides/index.md
      - Integrate Keptn with your Applications: guides/integrate.md
      - Evaluations: guides/evaluations.md
  - API Reference:
      - crd-ref/index.md
      - Lifecycle API:
          - crd-ref/lifecycle/index.md
          - v1alpha1: crd-ref/lifecycle/v1alpha1/index.md
          - v1alpha2: crd-ref/lifecycle/v1alpha2/index.md
          - v1alpha3: crd-ref/lifecycle/v1alpha3/index.md
          - v1alpha4: crd-ref/lifecycle/v1alpha4/index.md
